# -*- coding: utf-8 -*-
"""프로토타입(간단한 구상 코드).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kujXtk-1D3WPWyCzxeXMHZNcvov9odG3
"""

import random
import time

subway_line = {
    "역삼역": {"다음역": "선릉역", "평균_하차율": 0.3},
    "선릉역": {"다음역": "삼성역", "평균_하차율": 0.25},
    "삼성역": {"다음역": "봉은사역", "평균_하차율": 0.4},
    "봉은사역": {"다음역": "종합운동장역", "평균_하차율": 0.15},
}

def predict_alighting_passengers(current_station, current_passengers_in_car, user_past_data=None):

    if current_station not in subway_line:
        return 0, "알 수 없음"

    next_station_info = subway_line[current_station]
    avg_alighting_rate = next_station_info["평균_하차율"]

    predicted_alighting = int(current_passengers_in_car * avg_alighting_rate)

    if user_past_data and "frequent_alighting_station" in user_past_data:
        if user_past_data["frequent_alighting_station"] == next_station_info["다음역"]:
            predicted_alighting += random.randint(1, 3)

    predicted_alighting = min(predicted_alighting, current_passengers_in_car)

    return predicted_alighting, next_station_info["다음역"]

def subway_alighting_notification(user_id, current_station, current_passengers, user_past_data=None):

    predicted_alighting, next_station = predict_alighting_passengers(current_station, current_passengers, user_past_data)

    notification_message = f"[{user_id}님 알림]\n"
    notification_message += f"현재 '{current_station}' 다음 역은 '{next_station}'입니다.\n"

    if predicted_alighting > 0:
        seat_probability_message = ""
        if predicted_alighting >= 3:
            seat_probability_message = "곧 빈 좌석을 확보할 가능성이 높습니다!"
        elif predicted_alighting >= 1:
            seat_probability_message = "빈 좌석이 생길 수도 있습니다."
        else:
            seat_probability_message = "현재 칸은 여전히 혼잡할 수 있습니다."

        notification_message += f"'{next_station}'에서 약 {predicted_alighting}명이 하차할 것으로 예상됩니다. {seat_probability_message}\n"
    else:
        notification_message += f"'{next_station}'에서 큰 하차 변동은 없을 것으로 예상됩니다.\n"

    print(notification_message)

